import {
  Code2,
  Binary,
  Link,
  Clock,
  Palette,
  Search,
  Hash,
  MessageSquare,
  FileText,
  Table,
  Key,
  Lock,
} from 'lucide-react';
import type { Tool } from '../types/tools';

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON',
    icon: Code2,
    color: 'from-blue-500 to-cyan-500',
    category: 'web',
    description: '格式化',
  },
  {
    id: 'base64',
    name: 'Base64',
    icon: Binary,
    color: 'from-purple-500 to-pink-500',
    category: 'web',
    description: '编解码',
  },
  {
    id: 'url-encoder',
    name: 'URL',
    icon: Link,
    color: 'from-green-500 to-emerald-500',
    category: 'web',
    description: '编解码',
  },
  {
    id: 'timestamp',
    name: '时间戳',
    icon: Clock,
    color: 'from-orange-500 to-red-500',
    category: 'web',
    description: '转换',
  },
  {
    id: 'color-converter',
    name: '颜色',
    icon: Palette,
    color: 'from-pink-500 to-rose-500',
    category: 'web',
    description: '转换',
  },
  {
    id: 'regex-tester',
    name: '正则',
    icon: Search,
    color: 'from-indigo-500 to-blue-500',
    category: 'web',
    description: '测试',
  },
  {
    id: 'token-counter',
    name: 'Token',
    icon: Hash,
    color: 'from-violet-500 to-purple-500',
    category: 'ai',
    description: '计数',
  },
  {
    id: 'prompt-template',
    name: '提示词',
    icon: MessageSquare,
    color: 'from-cyan-500 to-teal-500',
    category: 'ai',
    description: '模板',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown',
    icon: FileText,
    color: 'from-emerald-500 to-green-500',
    category: 'ai',
    description: '预览',
  },
  {
    id: 'csv-to-json',
    name: 'CSV',
    icon: Table,
    color: 'from-amber-500 to-orange-500',
    category: 'ai',
    description: '转JSON',
  },
  {
    id: 'uuid-generator',
    name: 'UUID',
    icon: Key,
    color: 'from-rose-500 to-pink-500',
    category: 'ai',
    description: '生成',
  },
  {
    id: 'hash-calculator',
    name: 'Hash',
    icon: Lock,
    color: 'from-slate-500 to-gray-500',
    category: 'ai',
    description: '计算',
  },
];
